// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file zitadel/feature.proto (package zitadel.feature.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum zitadel.feature.v1.InstanceFeature
 */
export enum InstanceFeature {
  /**
   * @generated from enum value: INSTANCE_FEATURE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: INSTANCE_FEATURE_LOGIN_DEFAULT_ORG = 1;
   */
  LOGIN_DEFAULT_ORG = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(InstanceFeature)
proto3.util.setEnumType(InstanceFeature, "zitadel.feature.v1.InstanceFeature", [
  { no: 0, name: "INSTANCE_FEATURE_UNSPECIFIED" },
  { no: 1, name: "INSTANCE_FEATURE_LOGIN_DEFAULT_ORG" },
]);

