// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file zitadel/text.proto (package zitadel.text.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { ObjectDetails } from "./object_pb.js";

/**
 * @generated from message zitadel.text.v1.MessageCustomText
 */
export class MessageCustomText extends Message<MessageCustomText> {
  /**
   * @generated from field: zitadel.v1.ObjectDetails details = 1;
   */
  details?: ObjectDetails;

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string pre_header = 3;
   */
  preHeader = "";

  /**
   * @generated from field: string subject = 4;
   */
  subject = "";

  /**
   * @generated from field: string greeting = 5;
   */
  greeting = "";

  /**
   * @generated from field: string text = 6;
   */
  text = "";

  /**
   * @generated from field: string button_text = 7;
   */
  buttonText = "";

  /**
   * @generated from field: string footer_text = 8;
   */
  footerText = "";

  /**
   * @generated from field: bool is_default = 9;
   */
  isDefault = false;

  constructor(data?: PartialMessage<MessageCustomText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.MessageCustomText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "details", kind: "message", T: ObjectDetails },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "pre_header", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "greeting", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "footer_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "is_default", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageCustomText {
    return new MessageCustomText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageCustomText {
    return new MessageCustomText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageCustomText {
    return new MessageCustomText().fromJsonString(jsonString, options);
  }

  static equals(a: MessageCustomText | PlainMessage<MessageCustomText> | undefined, b: MessageCustomText | PlainMessage<MessageCustomText> | undefined): boolean {
    return proto3.util.equals(MessageCustomText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.LoginCustomText
 */
export class LoginCustomText extends Message<LoginCustomText> {
  /**
   * @generated from field: zitadel.v1.ObjectDetails details = 1;
   */
  details?: ObjectDetails;

  /**
   * @generated from field: zitadel.text.v1.SelectAccountScreenText select_account_text = 2;
   */
  selectAccountText?: SelectAccountScreenText;

  /**
   * @generated from field: zitadel.text.v1.LoginScreenText login_text = 3;
   */
  loginText?: LoginScreenText;

  /**
   * @generated from field: zitadel.text.v1.PasswordScreenText password_text = 4;
   */
  passwordText?: PasswordScreenText;

  /**
   * @generated from field: zitadel.text.v1.UsernameChangeScreenText username_change_text = 5;
   */
  usernameChangeText?: UsernameChangeScreenText;

  /**
   * @generated from field: zitadel.text.v1.UsernameChangeDoneScreenText username_change_done_text = 6;
   */
  usernameChangeDoneText?: UsernameChangeDoneScreenText;

  /**
   * @generated from field: zitadel.text.v1.InitPasswordScreenText init_password_text = 7;
   */
  initPasswordText?: InitPasswordScreenText;

  /**
   * @generated from field: zitadel.text.v1.InitPasswordDoneScreenText init_password_done_text = 8;
   */
  initPasswordDoneText?: InitPasswordDoneScreenText;

  /**
   * @generated from field: zitadel.text.v1.EmailVerificationScreenText email_verification_text = 9;
   */
  emailVerificationText?: EmailVerificationScreenText;

  /**
   * @generated from field: zitadel.text.v1.EmailVerificationDoneScreenText email_verification_done_text = 10;
   */
  emailVerificationDoneText?: EmailVerificationDoneScreenText;

  /**
   * @generated from field: zitadel.text.v1.InitializeUserScreenText initialize_user_text = 11;
   */
  initializeUserText?: InitializeUserScreenText;

  /**
   * @generated from field: zitadel.text.v1.InitializeUserDoneScreenText initialize_done_text = 12;
   */
  initializeDoneText?: InitializeUserDoneScreenText;

  /**
   * @generated from field: zitadel.text.v1.InitMFAPromptScreenText init_mfa_prompt_text = 13;
   */
  initMfaPromptText?: InitMFAPromptScreenText;

  /**
   * @generated from field: zitadel.text.v1.InitMFAOTPScreenText init_mfa_otp_text = 14;
   */
  initMfaOtpText?: InitMFAOTPScreenText;

  /**
   * @generated from field: zitadel.text.v1.InitMFAU2FScreenText init_mfa_u2f_text = 15;
   */
  initMfaU2fText?: InitMFAU2FScreenText;

  /**
   * @generated from field: zitadel.text.v1.InitMFADoneScreenText init_mfa_done_text = 16;
   */
  initMfaDoneText?: InitMFADoneScreenText;

  /**
   * @generated from field: zitadel.text.v1.MFAProvidersText mfa_providers_text = 17;
   */
  mfaProvidersText?: MFAProvidersText;

  /**
   * @generated from field: zitadel.text.v1.VerifyMFAOTPScreenText verify_mfa_otp_text = 18;
   */
  verifyMfaOtpText?: VerifyMFAOTPScreenText;

  /**
   * @generated from field: zitadel.text.v1.VerifyMFAU2FScreenText verify_mfa_u2f_text = 19;
   */
  verifyMfaU2fText?: VerifyMFAU2FScreenText;

  /**
   * @generated from field: zitadel.text.v1.PasswordlessScreenText passwordless_text = 20;
   */
  passwordlessText?: PasswordlessScreenText;

  /**
   * @generated from field: zitadel.text.v1.PasswordChangeScreenText password_change_text = 21;
   */
  passwordChangeText?: PasswordChangeScreenText;

  /**
   * @generated from field: zitadel.text.v1.PasswordChangeDoneScreenText password_change_done_text = 22;
   */
  passwordChangeDoneText?: PasswordChangeDoneScreenText;

  /**
   * @generated from field: zitadel.text.v1.PasswordResetDoneScreenText password_reset_done_text = 23;
   */
  passwordResetDoneText?: PasswordResetDoneScreenText;

  /**
   * @generated from field: zitadel.text.v1.RegistrationOptionScreenText registration_option_text = 24;
   */
  registrationOptionText?: RegistrationOptionScreenText;

  /**
   * @generated from field: zitadel.text.v1.RegistrationUserScreenText registration_user_text = 25;
   */
  registrationUserText?: RegistrationUserScreenText;

  /**
   * @generated from field: zitadel.text.v1.RegistrationOrgScreenText registration_org_text = 26;
   */
  registrationOrgText?: RegistrationOrgScreenText;

  /**
   * @generated from field: zitadel.text.v1.LinkingUserDoneScreenText linking_user_done_text = 27;
   */
  linkingUserDoneText?: LinkingUserDoneScreenText;

  /**
   * @generated from field: zitadel.text.v1.ExternalUserNotFoundScreenText external_user_not_found_text = 28;
   */
  externalUserNotFoundText?: ExternalUserNotFoundScreenText;

  /**
   * @generated from field: zitadel.text.v1.SuccessLoginScreenText success_login_text = 29;
   */
  successLoginText?: SuccessLoginScreenText;

  /**
   * @generated from field: zitadel.text.v1.LogoutDoneScreenText logout_text = 30;
   */
  logoutText?: LogoutDoneScreenText;

  /**
   * @generated from field: zitadel.text.v1.FooterText footer_text = 31;
   */
  footerText?: FooterText;

  /**
   * @generated from field: zitadel.text.v1.PasswordlessPromptScreenText passwordless_prompt_text = 32;
   */
  passwordlessPromptText?: PasswordlessPromptScreenText;

  /**
   * @generated from field: zitadel.text.v1.PasswordlessRegistrationScreenText passwordless_registration_text = 33;
   */
  passwordlessRegistrationText?: PasswordlessRegistrationScreenText;

  /**
   * @generated from field: zitadel.text.v1.PasswordlessRegistrationDoneScreenText passwordless_registration_done_text = 34;
   */
  passwordlessRegistrationDoneText?: PasswordlessRegistrationDoneScreenText;

  /**
   * @generated from field: zitadel.text.v1.ExternalRegistrationUserOverviewScreenText external_registration_user_overview_text = 35;
   */
  externalRegistrationUserOverviewText?: ExternalRegistrationUserOverviewScreenText;

  /**
   * @generated from field: bool is_default = 36;
   */
  isDefault = false;

  /**
   * @generated from field: zitadel.text.v1.LinkingUserPromptScreenText linking_user_prompt_text = 37;
   */
  linkingUserPromptText?: LinkingUserPromptScreenText;

  constructor(data?: PartialMessage<LoginCustomText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.LoginCustomText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "details", kind: "message", T: ObjectDetails },
    { no: 2, name: "select_account_text", kind: "message", T: SelectAccountScreenText },
    { no: 3, name: "login_text", kind: "message", T: LoginScreenText },
    { no: 4, name: "password_text", kind: "message", T: PasswordScreenText },
    { no: 5, name: "username_change_text", kind: "message", T: UsernameChangeScreenText },
    { no: 6, name: "username_change_done_text", kind: "message", T: UsernameChangeDoneScreenText },
    { no: 7, name: "init_password_text", kind: "message", T: InitPasswordScreenText },
    { no: 8, name: "init_password_done_text", kind: "message", T: InitPasswordDoneScreenText },
    { no: 9, name: "email_verification_text", kind: "message", T: EmailVerificationScreenText },
    { no: 10, name: "email_verification_done_text", kind: "message", T: EmailVerificationDoneScreenText },
    { no: 11, name: "initialize_user_text", kind: "message", T: InitializeUserScreenText },
    { no: 12, name: "initialize_done_text", kind: "message", T: InitializeUserDoneScreenText },
    { no: 13, name: "init_mfa_prompt_text", kind: "message", T: InitMFAPromptScreenText },
    { no: 14, name: "init_mfa_otp_text", kind: "message", T: InitMFAOTPScreenText },
    { no: 15, name: "init_mfa_u2f_text", kind: "message", T: InitMFAU2FScreenText },
    { no: 16, name: "init_mfa_done_text", kind: "message", T: InitMFADoneScreenText },
    { no: 17, name: "mfa_providers_text", kind: "message", T: MFAProvidersText },
    { no: 18, name: "verify_mfa_otp_text", kind: "message", T: VerifyMFAOTPScreenText },
    { no: 19, name: "verify_mfa_u2f_text", kind: "message", T: VerifyMFAU2FScreenText },
    { no: 20, name: "passwordless_text", kind: "message", T: PasswordlessScreenText },
    { no: 21, name: "password_change_text", kind: "message", T: PasswordChangeScreenText },
    { no: 22, name: "password_change_done_text", kind: "message", T: PasswordChangeDoneScreenText },
    { no: 23, name: "password_reset_done_text", kind: "message", T: PasswordResetDoneScreenText },
    { no: 24, name: "registration_option_text", kind: "message", T: RegistrationOptionScreenText },
    { no: 25, name: "registration_user_text", kind: "message", T: RegistrationUserScreenText },
    { no: 26, name: "registration_org_text", kind: "message", T: RegistrationOrgScreenText },
    { no: 27, name: "linking_user_done_text", kind: "message", T: LinkingUserDoneScreenText },
    { no: 28, name: "external_user_not_found_text", kind: "message", T: ExternalUserNotFoundScreenText },
    { no: 29, name: "success_login_text", kind: "message", T: SuccessLoginScreenText },
    { no: 30, name: "logout_text", kind: "message", T: LogoutDoneScreenText },
    { no: 31, name: "footer_text", kind: "message", T: FooterText },
    { no: 32, name: "passwordless_prompt_text", kind: "message", T: PasswordlessPromptScreenText },
    { no: 33, name: "passwordless_registration_text", kind: "message", T: PasswordlessRegistrationScreenText },
    { no: 34, name: "passwordless_registration_done_text", kind: "message", T: PasswordlessRegistrationDoneScreenText },
    { no: 35, name: "external_registration_user_overview_text", kind: "message", T: ExternalRegistrationUserOverviewScreenText },
    { no: 36, name: "is_default", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 37, name: "linking_user_prompt_text", kind: "message", T: LinkingUserPromptScreenText },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LoginCustomText {
    return new LoginCustomText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LoginCustomText {
    return new LoginCustomText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LoginCustomText {
    return new LoginCustomText().fromJsonString(jsonString, options);
  }

  static equals(a: LoginCustomText | PlainMessage<LoginCustomText> | undefined, b: LoginCustomText | PlainMessage<LoginCustomText> | undefined): boolean {
    return proto3.util.equals(LoginCustomText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.SelectAccountScreenText
 */
export class SelectAccountScreenText extends Message<SelectAccountScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string title_linking_process = 3;
   */
  titleLinkingProcess = "";

  /**
   * @generated from field: string description_linking_process = 4;
   */
  descriptionLinkingProcess = "";

  /**
   * @generated from field: string other_user = 5;
   */
  otherUser = "";

  /**
   * @generated from field: string session_state_active = 6;
   */
  sessionStateActive = "";

  /**
   * @generated from field: string session_state_inactive = 7;
   */
  sessionStateInactive = "";

  /**
   * @generated from field: string user_must_be_member_of_org = 8;
   */
  userMustBeMemberOfOrg = "";

  constructor(data?: PartialMessage<SelectAccountScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.SelectAccountScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "title_linking_process", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description_linking_process", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "other_user", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "session_state_active", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "session_state_inactive", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "user_must_be_member_of_org", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SelectAccountScreenText {
    return new SelectAccountScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SelectAccountScreenText {
    return new SelectAccountScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SelectAccountScreenText {
    return new SelectAccountScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: SelectAccountScreenText | PlainMessage<SelectAccountScreenText> | undefined, b: SelectAccountScreenText | PlainMessage<SelectAccountScreenText> | undefined): boolean {
    return proto3.util.equals(SelectAccountScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.LoginScreenText
 */
export class LoginScreenText extends Message<LoginScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string title_linking_process = 3;
   */
  titleLinkingProcess = "";

  /**
   * @generated from field: string description_linking_process = 4;
   */
  descriptionLinkingProcess = "";

  /**
   * @generated from field: string user_must_be_member_of_org = 5;
   */
  userMustBeMemberOfOrg = "";

  /**
   * @generated from field: string login_name_label = 6;
   */
  loginNameLabel = "";

  /**
   * @generated from field: string register_button_text = 7;
   */
  registerButtonText = "";

  /**
   * @generated from field: string next_button_text = 8;
   */
  nextButtonText = "";

  /**
   * @generated from field: string external_user_description = 9;
   */
  externalUserDescription = "";

  /**
   * @generated from field: string user_name_placeholder = 10;
   */
  userNamePlaceholder = "";

  /**
   * @generated from field: string login_name_placeholder = 11;
   */
  loginNamePlaceholder = "";

  constructor(data?: PartialMessage<LoginScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.LoginScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "title_linking_process", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description_linking_process", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "user_must_be_member_of_org", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "login_name_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "register_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "external_user_description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "user_name_placeholder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "login_name_placeholder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LoginScreenText {
    return new LoginScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LoginScreenText {
    return new LoginScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LoginScreenText {
    return new LoginScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: LoginScreenText | PlainMessage<LoginScreenText> | undefined, b: LoginScreenText | PlainMessage<LoginScreenText> | undefined): boolean {
    return proto3.util.equals(LoginScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.PasswordScreenText
 */
export class PasswordScreenText extends Message<PasswordScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string password_label = 3;
   */
  passwordLabel = "";

  /**
   * @generated from field: string reset_link_text = 4;
   */
  resetLinkText = "";

  /**
   * @generated from field: string back_button_text = 5;
   */
  backButtonText = "";

  /**
   * @generated from field: string next_button_text = 6;
   */
  nextButtonText = "";

  /**
   * @generated from field: string min_length = 7;
   */
  minLength = "";

  /**
   * @generated from field: string has_uppercase = 8;
   */
  hasUppercase = "";

  /**
   * @generated from field: string has_lowercase = 9;
   */
  hasLowercase = "";

  /**
   * @generated from field: string has_number = 10;
   */
  hasNumber = "";

  /**
   * @generated from field: string has_symbol = 11;
   */
  hasSymbol = "";

  /**
   * @generated from field: string confirmation = 12;
   */
  confirmation = "";

  constructor(data?: PartialMessage<PasswordScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.PasswordScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "password_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "reset_link_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "back_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "min_length", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "has_uppercase", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "has_lowercase", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "has_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "has_symbol", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "confirmation", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PasswordScreenText {
    return new PasswordScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PasswordScreenText {
    return new PasswordScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PasswordScreenText {
    return new PasswordScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: PasswordScreenText | PlainMessage<PasswordScreenText> | undefined, b: PasswordScreenText | PlainMessage<PasswordScreenText> | undefined): boolean {
    return proto3.util.equals(PasswordScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.UsernameChangeScreenText
 */
export class UsernameChangeScreenText extends Message<UsernameChangeScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string username_label = 3;
   */
  usernameLabel = "";

  /**
   * @generated from field: string cancel_button_text = 4;
   */
  cancelButtonText = "";

  /**
   * @generated from field: string next_button_text = 5;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<UsernameChangeScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.UsernameChangeScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "username_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "cancel_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsernameChangeScreenText {
    return new UsernameChangeScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsernameChangeScreenText {
    return new UsernameChangeScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsernameChangeScreenText {
    return new UsernameChangeScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: UsernameChangeScreenText | PlainMessage<UsernameChangeScreenText> | undefined, b: UsernameChangeScreenText | PlainMessage<UsernameChangeScreenText> | undefined): boolean {
    return proto3.util.equals(UsernameChangeScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.UsernameChangeDoneScreenText
 */
export class UsernameChangeDoneScreenText extends Message<UsernameChangeDoneScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string next_button_text = 3;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<UsernameChangeDoneScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.UsernameChangeDoneScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsernameChangeDoneScreenText {
    return new UsernameChangeDoneScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsernameChangeDoneScreenText {
    return new UsernameChangeDoneScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsernameChangeDoneScreenText {
    return new UsernameChangeDoneScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: UsernameChangeDoneScreenText | PlainMessage<UsernameChangeDoneScreenText> | undefined, b: UsernameChangeDoneScreenText | PlainMessage<UsernameChangeDoneScreenText> | undefined): boolean {
    return proto3.util.equals(UsernameChangeDoneScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.InitPasswordScreenText
 */
export class InitPasswordScreenText extends Message<InitPasswordScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string code_label = 3;
   */
  codeLabel = "";

  /**
   * @generated from field: string new_password_label = 4;
   */
  newPasswordLabel = "";

  /**
   * @generated from field: string new_password_confirm_label = 5;
   */
  newPasswordConfirmLabel = "";

  /**
   * @generated from field: string next_button_text = 6;
   */
  nextButtonText = "";

  /**
   * @generated from field: string resend_button_text = 7;
   */
  resendButtonText = "";

  constructor(data?: PartialMessage<InitPasswordScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.InitPasswordScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "code_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "new_password_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "new_password_confirm_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "resend_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitPasswordScreenText {
    return new InitPasswordScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitPasswordScreenText {
    return new InitPasswordScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitPasswordScreenText {
    return new InitPasswordScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: InitPasswordScreenText | PlainMessage<InitPasswordScreenText> | undefined, b: InitPasswordScreenText | PlainMessage<InitPasswordScreenText> | undefined): boolean {
    return proto3.util.equals(InitPasswordScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.InitPasswordDoneScreenText
 */
export class InitPasswordDoneScreenText extends Message<InitPasswordDoneScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string next_button_text = 3;
   */
  nextButtonText = "";

  /**
   * @generated from field: string cancel_button_text = 4;
   */
  cancelButtonText = "";

  constructor(data?: PartialMessage<InitPasswordDoneScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.InitPasswordDoneScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "cancel_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitPasswordDoneScreenText {
    return new InitPasswordDoneScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitPasswordDoneScreenText {
    return new InitPasswordDoneScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitPasswordDoneScreenText {
    return new InitPasswordDoneScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: InitPasswordDoneScreenText | PlainMessage<InitPasswordDoneScreenText> | undefined, b: InitPasswordDoneScreenText | PlainMessage<InitPasswordDoneScreenText> | undefined): boolean {
    return proto3.util.equals(InitPasswordDoneScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.EmailVerificationScreenText
 */
export class EmailVerificationScreenText extends Message<EmailVerificationScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string code_label = 3;
   */
  codeLabel = "";

  /**
   * @generated from field: string next_button_text = 4;
   */
  nextButtonText = "";

  /**
   * @generated from field: string resend_button_text = 5;
   */
  resendButtonText = "";

  constructor(data?: PartialMessage<EmailVerificationScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.EmailVerificationScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "code_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "resend_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EmailVerificationScreenText {
    return new EmailVerificationScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EmailVerificationScreenText {
    return new EmailVerificationScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EmailVerificationScreenText {
    return new EmailVerificationScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: EmailVerificationScreenText | PlainMessage<EmailVerificationScreenText> | undefined, b: EmailVerificationScreenText | PlainMessage<EmailVerificationScreenText> | undefined): boolean {
    return proto3.util.equals(EmailVerificationScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.EmailVerificationDoneScreenText
 */
export class EmailVerificationDoneScreenText extends Message<EmailVerificationDoneScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string next_button_text = 3;
   */
  nextButtonText = "";

  /**
   * @generated from field: string cancel_button_text = 4;
   */
  cancelButtonText = "";

  /**
   * @generated from field: string login_button_text = 5;
   */
  loginButtonText = "";

  constructor(data?: PartialMessage<EmailVerificationDoneScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.EmailVerificationDoneScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "cancel_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "login_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EmailVerificationDoneScreenText {
    return new EmailVerificationDoneScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EmailVerificationDoneScreenText {
    return new EmailVerificationDoneScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EmailVerificationDoneScreenText {
    return new EmailVerificationDoneScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: EmailVerificationDoneScreenText | PlainMessage<EmailVerificationDoneScreenText> | undefined, b: EmailVerificationDoneScreenText | PlainMessage<EmailVerificationDoneScreenText> | undefined): boolean {
    return proto3.util.equals(EmailVerificationDoneScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.InitializeUserScreenText
 */
export class InitializeUserScreenText extends Message<InitializeUserScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string code_label = 3;
   */
  codeLabel = "";

  /**
   * @generated from field: string new_password_label = 4;
   */
  newPasswordLabel = "";

  /**
   * @generated from field: string new_password_confirm_label = 5;
   */
  newPasswordConfirmLabel = "";

  /**
   * @generated from field: string resend_button_text = 6;
   */
  resendButtonText = "";

  /**
   * @generated from field: string next_button_text = 7;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<InitializeUserScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.InitializeUserScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "code_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "new_password_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "new_password_confirm_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "resend_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitializeUserScreenText {
    return new InitializeUserScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitializeUserScreenText {
    return new InitializeUserScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitializeUserScreenText {
    return new InitializeUserScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: InitializeUserScreenText | PlainMessage<InitializeUserScreenText> | undefined, b: InitializeUserScreenText | PlainMessage<InitializeUserScreenText> | undefined): boolean {
    return proto3.util.equals(InitializeUserScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.InitializeUserDoneScreenText
 */
export class InitializeUserDoneScreenText extends Message<InitializeUserDoneScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string cancel_button_text = 3;
   */
  cancelButtonText = "";

  /**
   * @generated from field: string next_button_text = 4;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<InitializeUserDoneScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.InitializeUserDoneScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "cancel_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitializeUserDoneScreenText {
    return new InitializeUserDoneScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitializeUserDoneScreenText {
    return new InitializeUserDoneScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitializeUserDoneScreenText {
    return new InitializeUserDoneScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: InitializeUserDoneScreenText | PlainMessage<InitializeUserDoneScreenText> | undefined, b: InitializeUserDoneScreenText | PlainMessage<InitializeUserDoneScreenText> | undefined): boolean {
    return proto3.util.equals(InitializeUserDoneScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.InitMFAPromptScreenText
 */
export class InitMFAPromptScreenText extends Message<InitMFAPromptScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string otp_option = 3;
   */
  otpOption = "";

  /**
   * @generated from field: string u2f_option = 4;
   */
  u2fOption = "";

  /**
   * @generated from field: string skip_button_text = 5;
   */
  skipButtonText = "";

  /**
   * @generated from field: string next_button_text = 6;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<InitMFAPromptScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.InitMFAPromptScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "otp_option", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "u2f_option", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "skip_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitMFAPromptScreenText {
    return new InitMFAPromptScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitMFAPromptScreenText {
    return new InitMFAPromptScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitMFAPromptScreenText {
    return new InitMFAPromptScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: InitMFAPromptScreenText | PlainMessage<InitMFAPromptScreenText> | undefined, b: InitMFAPromptScreenText | PlainMessage<InitMFAPromptScreenText> | undefined): boolean {
    return proto3.util.equals(InitMFAPromptScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.InitMFAOTPScreenText
 */
export class InitMFAOTPScreenText extends Message<InitMFAOTPScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string description_otp = 3;
   */
  descriptionOtp = "";

  /**
   * @generated from field: string secret_label = 4;
   */
  secretLabel = "";

  /**
   * @generated from field: string code_label = 5;
   */
  codeLabel = "";

  /**
   * @generated from field: string next_button_text = 6;
   */
  nextButtonText = "";

  /**
   * @generated from field: string cancel_button_text = 7;
   */
  cancelButtonText = "";

  constructor(data?: PartialMessage<InitMFAOTPScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.InitMFAOTPScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description_otp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "secret_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "code_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "cancel_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitMFAOTPScreenText {
    return new InitMFAOTPScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitMFAOTPScreenText {
    return new InitMFAOTPScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitMFAOTPScreenText {
    return new InitMFAOTPScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: InitMFAOTPScreenText | PlainMessage<InitMFAOTPScreenText> | undefined, b: InitMFAOTPScreenText | PlainMessage<InitMFAOTPScreenText> | undefined): boolean {
    return proto3.util.equals(InitMFAOTPScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.InitMFAU2FScreenText
 */
export class InitMFAU2FScreenText extends Message<InitMFAU2FScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string token_name_label = 3;
   */
  tokenNameLabel = "";

  /**
   * @generated from field: string not_supported = 4;
   */
  notSupported = "";

  /**
   * @generated from field: string register_token_button_text = 5;
   */
  registerTokenButtonText = "";

  /**
   * @generated from field: string error_retry = 6;
   */
  errorRetry = "";

  constructor(data?: PartialMessage<InitMFAU2FScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.InitMFAU2FScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "token_name_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "not_supported", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "register_token_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "error_retry", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitMFAU2FScreenText {
    return new InitMFAU2FScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitMFAU2FScreenText {
    return new InitMFAU2FScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitMFAU2FScreenText {
    return new InitMFAU2FScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: InitMFAU2FScreenText | PlainMessage<InitMFAU2FScreenText> | undefined, b: InitMFAU2FScreenText | PlainMessage<InitMFAU2FScreenText> | undefined): boolean {
    return proto3.util.equals(InitMFAU2FScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.InitMFADoneScreenText
 */
export class InitMFADoneScreenText extends Message<InitMFADoneScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string cancel_button_text = 3;
   */
  cancelButtonText = "";

  /**
   * @generated from field: string next_button_text = 4;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<InitMFADoneScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.InitMFADoneScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "cancel_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InitMFADoneScreenText {
    return new InitMFADoneScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InitMFADoneScreenText {
    return new InitMFADoneScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InitMFADoneScreenText {
    return new InitMFADoneScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: InitMFADoneScreenText | PlainMessage<InitMFADoneScreenText> | undefined, b: InitMFADoneScreenText | PlainMessage<InitMFADoneScreenText> | undefined): boolean {
    return proto3.util.equals(InitMFADoneScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.MFAProvidersText
 */
export class MFAProvidersText extends Message<MFAProvidersText> {
  /**
   * @generated from field: string choose_other = 1;
   */
  chooseOther = "";

  /**
   * @generated from field: string otp = 2;
   */
  otp = "";

  /**
   * @generated from field: string u2f = 3;
   */
  u2f = "";

  constructor(data?: PartialMessage<MFAProvidersText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.MFAProvidersText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "choose_other", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "otp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "u2f", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MFAProvidersText {
    return new MFAProvidersText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MFAProvidersText {
    return new MFAProvidersText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MFAProvidersText {
    return new MFAProvidersText().fromJsonString(jsonString, options);
  }

  static equals(a: MFAProvidersText | PlainMessage<MFAProvidersText> | undefined, b: MFAProvidersText | PlainMessage<MFAProvidersText> | undefined): boolean {
    return proto3.util.equals(MFAProvidersText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.VerifyMFAOTPScreenText
 */
export class VerifyMFAOTPScreenText extends Message<VerifyMFAOTPScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string code_label = 3;
   */
  codeLabel = "";

  /**
   * @generated from field: string next_button_text = 4;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<VerifyMFAOTPScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.VerifyMFAOTPScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "code_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VerifyMFAOTPScreenText {
    return new VerifyMFAOTPScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VerifyMFAOTPScreenText {
    return new VerifyMFAOTPScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VerifyMFAOTPScreenText {
    return new VerifyMFAOTPScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: VerifyMFAOTPScreenText | PlainMessage<VerifyMFAOTPScreenText> | undefined, b: VerifyMFAOTPScreenText | PlainMessage<VerifyMFAOTPScreenText> | undefined): boolean {
    return proto3.util.equals(VerifyMFAOTPScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.VerifyMFAU2FScreenText
 */
export class VerifyMFAU2FScreenText extends Message<VerifyMFAU2FScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string validate_token_text = 3;
   */
  validateTokenText = "";

  /**
   * @generated from field: string not_supported = 4;
   */
  notSupported = "";

  /**
   * @generated from field: string error_retry = 5;
   */
  errorRetry = "";

  constructor(data?: PartialMessage<VerifyMFAU2FScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.VerifyMFAU2FScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "validate_token_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "not_supported", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "error_retry", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VerifyMFAU2FScreenText {
    return new VerifyMFAU2FScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VerifyMFAU2FScreenText {
    return new VerifyMFAU2FScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VerifyMFAU2FScreenText {
    return new VerifyMFAU2FScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: VerifyMFAU2FScreenText | PlainMessage<VerifyMFAU2FScreenText> | undefined, b: VerifyMFAU2FScreenText | PlainMessage<VerifyMFAU2FScreenText> | undefined): boolean {
    return proto3.util.equals(VerifyMFAU2FScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.PasswordlessScreenText
 */
export class PasswordlessScreenText extends Message<PasswordlessScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string login_with_pw_button_text = 3;
   */
  loginWithPwButtonText = "";

  /**
   * @generated from field: string validate_token_button_text = 4;
   */
  validateTokenButtonText = "";

  /**
   * @generated from field: string not_supported = 5;
   */
  notSupported = "";

  /**
   * @generated from field: string error_retry = 6;
   */
  errorRetry = "";

  constructor(data?: PartialMessage<PasswordlessScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.PasswordlessScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "login_with_pw_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "validate_token_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "not_supported", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "error_retry", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PasswordlessScreenText {
    return new PasswordlessScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PasswordlessScreenText {
    return new PasswordlessScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PasswordlessScreenText {
    return new PasswordlessScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: PasswordlessScreenText | PlainMessage<PasswordlessScreenText> | undefined, b: PasswordlessScreenText | PlainMessage<PasswordlessScreenText> | undefined): boolean {
    return proto3.util.equals(PasswordlessScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.PasswordChangeScreenText
 */
export class PasswordChangeScreenText extends Message<PasswordChangeScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string old_password_label = 3;
   */
  oldPasswordLabel = "";

  /**
   * @generated from field: string new_password_label = 4;
   */
  newPasswordLabel = "";

  /**
   * @generated from field: string new_password_confirm_label = 5;
   */
  newPasswordConfirmLabel = "";

  /**
   * @generated from field: string cancel_button_text = 6;
   */
  cancelButtonText = "";

  /**
   * @generated from field: string next_button_text = 7;
   */
  nextButtonText = "";

  /**
   * @generated from field: string expired_description = 8;
   */
  expiredDescription = "";

  constructor(data?: PartialMessage<PasswordChangeScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.PasswordChangeScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "old_password_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "new_password_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "new_password_confirm_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "cancel_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "expired_description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PasswordChangeScreenText {
    return new PasswordChangeScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PasswordChangeScreenText {
    return new PasswordChangeScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PasswordChangeScreenText {
    return new PasswordChangeScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: PasswordChangeScreenText | PlainMessage<PasswordChangeScreenText> | undefined, b: PasswordChangeScreenText | PlainMessage<PasswordChangeScreenText> | undefined): boolean {
    return proto3.util.equals(PasswordChangeScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.PasswordChangeDoneScreenText
 */
export class PasswordChangeDoneScreenText extends Message<PasswordChangeDoneScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string next_button_text = 3;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<PasswordChangeDoneScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.PasswordChangeDoneScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PasswordChangeDoneScreenText {
    return new PasswordChangeDoneScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PasswordChangeDoneScreenText {
    return new PasswordChangeDoneScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PasswordChangeDoneScreenText {
    return new PasswordChangeDoneScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: PasswordChangeDoneScreenText | PlainMessage<PasswordChangeDoneScreenText> | undefined, b: PasswordChangeDoneScreenText | PlainMessage<PasswordChangeDoneScreenText> | undefined): boolean {
    return proto3.util.equals(PasswordChangeDoneScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.PasswordResetDoneScreenText
 */
export class PasswordResetDoneScreenText extends Message<PasswordResetDoneScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string next_button_text = 3;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<PasswordResetDoneScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.PasswordResetDoneScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PasswordResetDoneScreenText {
    return new PasswordResetDoneScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PasswordResetDoneScreenText {
    return new PasswordResetDoneScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PasswordResetDoneScreenText {
    return new PasswordResetDoneScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: PasswordResetDoneScreenText | PlainMessage<PasswordResetDoneScreenText> | undefined, b: PasswordResetDoneScreenText | PlainMessage<PasswordResetDoneScreenText> | undefined): boolean {
    return proto3.util.equals(PasswordResetDoneScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.RegistrationOptionScreenText
 */
export class RegistrationOptionScreenText extends Message<RegistrationOptionScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string user_name_button_text = 3;
   */
  userNameButtonText = "";

  /**
   * @generated from field: string external_login_description = 4;
   */
  externalLoginDescription = "";

  /**
   * @generated from field: string login_button_text = 5;
   */
  loginButtonText = "";

  constructor(data?: PartialMessage<RegistrationOptionScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.RegistrationOptionScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "user_name_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "external_login_description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "login_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegistrationOptionScreenText {
    return new RegistrationOptionScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegistrationOptionScreenText {
    return new RegistrationOptionScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegistrationOptionScreenText {
    return new RegistrationOptionScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: RegistrationOptionScreenText | PlainMessage<RegistrationOptionScreenText> | undefined, b: RegistrationOptionScreenText | PlainMessage<RegistrationOptionScreenText> | undefined): boolean {
    return proto3.util.equals(RegistrationOptionScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.RegistrationUserScreenText
 */
export class RegistrationUserScreenText extends Message<RegistrationUserScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string description_org_register = 3;
   */
  descriptionOrgRegister = "";

  /**
   * @generated from field: string firstname_label = 4;
   */
  firstnameLabel = "";

  /**
   * @generated from field: string lastname_label = 5;
   */
  lastnameLabel = "";

  /**
   * @generated from field: string email_label = 6;
   */
  emailLabel = "";

  /**
   * @generated from field: string username_label = 7;
   */
  usernameLabel = "";

  /**
   * @generated from field: string language_label = 8;
   */
  languageLabel = "";

  /**
   * @generated from field: string gender_label = 9;
   */
  genderLabel = "";

  /**
   * @generated from field: string password_label = 10;
   */
  passwordLabel = "";

  /**
   * @generated from field: string password_confirm_label = 11;
   */
  passwordConfirmLabel = "";

  /**
   * @generated from field: string tos_and_privacy_label = 12;
   */
  tosAndPrivacyLabel = "";

  /**
   * @generated from field: string tos_confirm = 13;
   */
  tosConfirm = "";

  /**
   * @generated from field: string tos_link_text = 15;
   */
  tosLinkText = "";

  /**
   * @generated from field: string privacy_confirm = 16;
   */
  privacyConfirm = "";

  /**
   * @generated from field: string privacy_link_text = 18;
   */
  privacyLinkText = "";

  /**
   * @generated from field: string next_button_text = 20;
   */
  nextButtonText = "";

  /**
   * @generated from field: string back_button_text = 21;
   */
  backButtonText = "";

  constructor(data?: PartialMessage<RegistrationUserScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.RegistrationUserScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description_org_register", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "firstname_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "lastname_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "email_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "username_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "language_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "gender_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "password_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "password_confirm_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "tos_and_privacy_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "tos_confirm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "tos_link_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "privacy_confirm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 18, name: "privacy_link_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 20, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 21, name: "back_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegistrationUserScreenText {
    return new RegistrationUserScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegistrationUserScreenText {
    return new RegistrationUserScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegistrationUserScreenText {
    return new RegistrationUserScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: RegistrationUserScreenText | PlainMessage<RegistrationUserScreenText> | undefined, b: RegistrationUserScreenText | PlainMessage<RegistrationUserScreenText> | undefined): boolean {
    return proto3.util.equals(RegistrationUserScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.ExternalRegistrationUserOverviewScreenText
 */
export class ExternalRegistrationUserOverviewScreenText extends Message<ExternalRegistrationUserOverviewScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string email_label = 3;
   */
  emailLabel = "";

  /**
   * @generated from field: string username_label = 4;
   */
  usernameLabel = "";

  /**
   * @generated from field: string firstname_label = 5;
   */
  firstnameLabel = "";

  /**
   * @generated from field: string lastname_label = 6;
   */
  lastnameLabel = "";

  /**
   * @generated from field: string nickname_label = 7;
   */
  nicknameLabel = "";

  /**
   * @generated from field: string language_label = 8;
   */
  languageLabel = "";

  /**
   * @generated from field: string phone_label = 9;
   */
  phoneLabel = "";

  /**
   * @generated from field: string tos_and_privacy_label = 10;
   */
  tosAndPrivacyLabel = "";

  /**
   * @generated from field: string tos_confirm = 11;
   */
  tosConfirm = "";

  /**
   * @generated from field: string tos_link_text = 12;
   */
  tosLinkText = "";

  /**
   * @generated from field: string privacy_link_text = 14;
   */
  privacyLinkText = "";

  /**
   * @generated from field: string back_button_text = 15;
   */
  backButtonText = "";

  /**
   * @generated from field: string next_button_text = 16;
   */
  nextButtonText = "";

  /**
   * @generated from field: string privacy_confirm = 17;
   */
  privacyConfirm = "";

  constructor(data?: PartialMessage<ExternalRegistrationUserOverviewScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.ExternalRegistrationUserOverviewScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "username_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "firstname_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "lastname_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "nickname_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "language_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "phone_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "tos_and_privacy_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "tos_confirm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "tos_link_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "privacy_link_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "back_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "privacy_confirm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExternalRegistrationUserOverviewScreenText {
    return new ExternalRegistrationUserOverviewScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExternalRegistrationUserOverviewScreenText {
    return new ExternalRegistrationUserOverviewScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExternalRegistrationUserOverviewScreenText {
    return new ExternalRegistrationUserOverviewScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: ExternalRegistrationUserOverviewScreenText | PlainMessage<ExternalRegistrationUserOverviewScreenText> | undefined, b: ExternalRegistrationUserOverviewScreenText | PlainMessage<ExternalRegistrationUserOverviewScreenText> | undefined): boolean {
    return proto3.util.equals(ExternalRegistrationUserOverviewScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.RegistrationOrgScreenText
 */
export class RegistrationOrgScreenText extends Message<RegistrationOrgScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string orgname_label = 3;
   */
  orgnameLabel = "";

  /**
   * @generated from field: string firstname_label = 4;
   */
  firstnameLabel = "";

  /**
   * @generated from field: string lastname_label = 5;
   */
  lastnameLabel = "";

  /**
   * @generated from field: string username_label = 6;
   */
  usernameLabel = "";

  /**
   * @generated from field: string email_label = 7;
   */
  emailLabel = "";

  /**
   * @generated from field: string password_label = 9;
   */
  passwordLabel = "";

  /**
   * @generated from field: string password_confirm_label = 10;
   */
  passwordConfirmLabel = "";

  /**
   * @generated from field: string tos_and_privacy_label = 11;
   */
  tosAndPrivacyLabel = "";

  /**
   * @generated from field: string tos_confirm = 12;
   */
  tosConfirm = "";

  /**
   * @generated from field: string tos_link_text = 14;
   */
  tosLinkText = "";

  /**
   * @generated from field: string privacy_confirm = 15;
   */
  privacyConfirm = "";

  /**
   * @generated from field: string privacy_link_text = 17;
   */
  privacyLinkText = "";

  /**
   * @generated from field: string save_button_text = 19;
   */
  saveButtonText = "";

  constructor(data?: PartialMessage<RegistrationOrgScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.RegistrationOrgScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "orgname_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "firstname_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "lastname_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "username_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "email_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "password_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "password_confirm_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "tos_and_privacy_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "tos_confirm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "tos_link_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "privacy_confirm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "privacy_link_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 19, name: "save_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegistrationOrgScreenText {
    return new RegistrationOrgScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegistrationOrgScreenText {
    return new RegistrationOrgScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegistrationOrgScreenText {
    return new RegistrationOrgScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: RegistrationOrgScreenText | PlainMessage<RegistrationOrgScreenText> | undefined, b: RegistrationOrgScreenText | PlainMessage<RegistrationOrgScreenText> | undefined): boolean {
    return proto3.util.equals(RegistrationOrgScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.LinkingUserPromptScreenText
 */
export class LinkingUserPromptScreenText extends Message<LinkingUserPromptScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string link_button_text = 3;
   */
  linkButtonText = "";

  /**
   * @generated from field: string other_button_text = 4;
   */
  otherButtonText = "";

  constructor(data?: PartialMessage<LinkingUserPromptScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.LinkingUserPromptScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "link_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "other_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LinkingUserPromptScreenText {
    return new LinkingUserPromptScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LinkingUserPromptScreenText {
    return new LinkingUserPromptScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LinkingUserPromptScreenText {
    return new LinkingUserPromptScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: LinkingUserPromptScreenText | PlainMessage<LinkingUserPromptScreenText> | undefined, b: LinkingUserPromptScreenText | PlainMessage<LinkingUserPromptScreenText> | undefined): boolean {
    return proto3.util.equals(LinkingUserPromptScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.LinkingUserDoneScreenText
 */
export class LinkingUserDoneScreenText extends Message<LinkingUserDoneScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string cancel_button_text = 3;
   */
  cancelButtonText = "";

  /**
   * @generated from field: string next_button_text = 4;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<LinkingUserDoneScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.LinkingUserDoneScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "cancel_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LinkingUserDoneScreenText {
    return new LinkingUserDoneScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LinkingUserDoneScreenText {
    return new LinkingUserDoneScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LinkingUserDoneScreenText {
    return new LinkingUserDoneScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: LinkingUserDoneScreenText | PlainMessage<LinkingUserDoneScreenText> | undefined, b: LinkingUserDoneScreenText | PlainMessage<LinkingUserDoneScreenText> | undefined): boolean {
    return proto3.util.equals(LinkingUserDoneScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.ExternalUserNotFoundScreenText
 */
export class ExternalUserNotFoundScreenText extends Message<ExternalUserNotFoundScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string link_button_text = 3;
   */
  linkButtonText = "";

  /**
   * @generated from field: string auto_register_button_text = 4;
   */
  autoRegisterButtonText = "";

  /**
   * @generated from field: string tos_and_privacy_label = 5;
   */
  tosAndPrivacyLabel = "";

  /**
   * @generated from field: string tos_confirm = 6;
   */
  tosConfirm = "";

  /**
   * @generated from field: string tos_link_text = 7;
   */
  tosLinkText = "";

  /**
   * @generated from field: string privacy_link_text = 8;
   */
  privacyLinkText = "";

  /**
   * @generated from field: string privacy_confirm = 10;
   */
  privacyConfirm = "";

  constructor(data?: PartialMessage<ExternalUserNotFoundScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.ExternalUserNotFoundScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "link_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "auto_register_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "tos_and_privacy_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "tos_confirm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "tos_link_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "privacy_link_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "privacy_confirm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExternalUserNotFoundScreenText {
    return new ExternalUserNotFoundScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExternalUserNotFoundScreenText {
    return new ExternalUserNotFoundScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExternalUserNotFoundScreenText {
    return new ExternalUserNotFoundScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: ExternalUserNotFoundScreenText | PlainMessage<ExternalUserNotFoundScreenText> | undefined, b: ExternalUserNotFoundScreenText | PlainMessage<ExternalUserNotFoundScreenText> | undefined): boolean {
    return proto3.util.equals(ExternalUserNotFoundScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.SuccessLoginScreenText
 */
export class SuccessLoginScreenText extends Message<SuccessLoginScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * Text to describe that auto-redirect should happen after successful login
   *
   * @generated from field: string auto_redirect_description = 2;
   */
  autoRedirectDescription = "";

  /**
   * Text to describe that the window can be closed after redirect
   *
   * @generated from field: string redirected_description = 3;
   */
  redirectedDescription = "";

  /**
   * @generated from field: string next_button_text = 4;
   */
  nextButtonText = "";

  constructor(data?: PartialMessage<SuccessLoginScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.SuccessLoginScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "auto_redirect_description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "redirected_description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SuccessLoginScreenText {
    return new SuccessLoginScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SuccessLoginScreenText {
    return new SuccessLoginScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SuccessLoginScreenText {
    return new SuccessLoginScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: SuccessLoginScreenText | PlainMessage<SuccessLoginScreenText> | undefined, b: SuccessLoginScreenText | PlainMessage<SuccessLoginScreenText> | undefined): boolean {
    return proto3.util.equals(SuccessLoginScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.LogoutDoneScreenText
 */
export class LogoutDoneScreenText extends Message<LogoutDoneScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string login_button_text = 3;
   */
  loginButtonText = "";

  constructor(data?: PartialMessage<LogoutDoneScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.LogoutDoneScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "login_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogoutDoneScreenText {
    return new LogoutDoneScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogoutDoneScreenText {
    return new LogoutDoneScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogoutDoneScreenText {
    return new LogoutDoneScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: LogoutDoneScreenText | PlainMessage<LogoutDoneScreenText> | undefined, b: LogoutDoneScreenText | PlainMessage<LogoutDoneScreenText> | undefined): boolean {
    return proto3.util.equals(LogoutDoneScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.FooterText
 */
export class FooterText extends Message<FooterText> {
  /**
   * @generated from field: string tos = 1;
   */
  tos = "";

  /**
   * @generated from field: string privacy_policy = 3;
   */
  privacyPolicy = "";

  /**
   * @generated from field: string help = 5;
   */
  help = "";

  /**
   * @generated from field: string support_email = 7;
   */
  supportEmail = "";

  constructor(data?: PartialMessage<FooterText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.FooterText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tos", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "privacy_policy", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "help", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "support_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FooterText {
    return new FooterText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FooterText {
    return new FooterText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FooterText {
    return new FooterText().fromJsonString(jsonString, options);
  }

  static equals(a: FooterText | PlainMessage<FooterText> | undefined, b: FooterText | PlainMessage<FooterText> | undefined): boolean {
    return proto3.util.equals(FooterText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.PasswordlessPromptScreenText
 */
export class PasswordlessPromptScreenText extends Message<PasswordlessPromptScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string description_init = 3;
   */
  descriptionInit = "";

  /**
   * @generated from field: string passwordless_button_text = 4;
   */
  passwordlessButtonText = "";

  /**
   * @generated from field: string next_button_text = 5;
   */
  nextButtonText = "";

  /**
   * @generated from field: string skip_button_text = 6;
   */
  skipButtonText = "";

  constructor(data?: PartialMessage<PasswordlessPromptScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.PasswordlessPromptScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description_init", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "passwordless_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "skip_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PasswordlessPromptScreenText {
    return new PasswordlessPromptScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PasswordlessPromptScreenText {
    return new PasswordlessPromptScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PasswordlessPromptScreenText {
    return new PasswordlessPromptScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: PasswordlessPromptScreenText | PlainMessage<PasswordlessPromptScreenText> | undefined, b: PasswordlessPromptScreenText | PlainMessage<PasswordlessPromptScreenText> | undefined): boolean {
    return proto3.util.equals(PasswordlessPromptScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.PasswordlessRegistrationScreenText
 */
export class PasswordlessRegistrationScreenText extends Message<PasswordlessRegistrationScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string token_name_label = 3;
   */
  tokenNameLabel = "";

  /**
   * @generated from field: string not_supported = 4;
   */
  notSupported = "";

  /**
   * @generated from field: string register_token_button_text = 5;
   */
  registerTokenButtonText = "";

  /**
   * @generated from field: string error_retry = 6;
   */
  errorRetry = "";

  constructor(data?: PartialMessage<PasswordlessRegistrationScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.PasswordlessRegistrationScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "token_name_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "not_supported", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "register_token_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "error_retry", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PasswordlessRegistrationScreenText {
    return new PasswordlessRegistrationScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PasswordlessRegistrationScreenText {
    return new PasswordlessRegistrationScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PasswordlessRegistrationScreenText {
    return new PasswordlessRegistrationScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: PasswordlessRegistrationScreenText | PlainMessage<PasswordlessRegistrationScreenText> | undefined, b: PasswordlessRegistrationScreenText | PlainMessage<PasswordlessRegistrationScreenText> | undefined): boolean {
    return proto3.util.equals(PasswordlessRegistrationScreenText, a, b);
  }
}

/**
 * @generated from message zitadel.text.v1.PasswordlessRegistrationDoneScreenText
 */
export class PasswordlessRegistrationDoneScreenText extends Message<PasswordlessRegistrationDoneScreenText> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string next_button_text = 3;
   */
  nextButtonText = "";

  /**
   * @generated from field: string cancel_button_text = 4;
   */
  cancelButtonText = "";

  /**
   * @generated from field: string description_close = 5;
   */
  descriptionClose = "";

  constructor(data?: PartialMessage<PasswordlessRegistrationDoneScreenText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.text.v1.PasswordlessRegistrationDoneScreenText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "next_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "cancel_button_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "description_close", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PasswordlessRegistrationDoneScreenText {
    return new PasswordlessRegistrationDoneScreenText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PasswordlessRegistrationDoneScreenText {
    return new PasswordlessRegistrationDoneScreenText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PasswordlessRegistrationDoneScreenText {
    return new PasswordlessRegistrationDoneScreenText().fromJsonString(jsonString, options);
  }

  static equals(a: PasswordlessRegistrationDoneScreenText | PlainMessage<PasswordlessRegistrationDoneScreenText> | undefined, b: PasswordlessRegistrationDoneScreenText | PlainMessage<PasswordlessRegistrationDoneScreenText> | undefined): boolean {
    return proto3.util.equals(PasswordlessRegistrationDoneScreenText, a, b);
  }
}

