// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file zitadel/settings/v2beta/settings.proto (package zitadel.settings.v2beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum zitadel.settings.v2beta.ResourceOwnerType
 */
export enum ResourceOwnerType {
  /**
   * @generated from enum value: RESOURCE_OWNER_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RESOURCE_OWNER_TYPE_INSTANCE = 1;
   */
  INSTANCE = 1,

  /**
   * @generated from enum value: RESOURCE_OWNER_TYPE_ORG = 2;
   */
  ORG = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(ResourceOwnerType)
proto3.util.setEnumType(ResourceOwnerType, "zitadel.settings.v2beta.ResourceOwnerType", [
  { no: 0, name: "RESOURCE_OWNER_TYPE_UNSPECIFIED" },
  { no: 1, name: "RESOURCE_OWNER_TYPE_INSTANCE" },
  { no: 2, name: "RESOURCE_OWNER_TYPE_ORG" },
]);

