// @generated by protoc-gen-es v1.8.0
// @generated from file zitadel/action/v3alpha/execution.proto (package zitadel.action.v3alpha, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Details } from "../../object/v2beta/object_pb.js";

/**
 * @generated from message zitadel.action.v3alpha.Execution
 */
export const Execution = /*@__PURE__*/ proto3.makeMessageType(
  "zitadel.action.v3alpha.Execution",
  () => [
    { no: 1, name: "execution_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "details", kind: "message", T: Details },
    { no: 3, name: "targets", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "includes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message zitadel.action.v3alpha.Condition
 */
export const Condition = /*@__PURE__*/ proto3.makeMessageType(
  "zitadel.action.v3alpha.Condition",
  () => [
    { no: 1, name: "request", kind: "message", T: RequestExecution, oneof: "condition_type" },
    { no: 2, name: "response", kind: "message", T: ResponseExecution, oneof: "condition_type" },
    { no: 3, name: "function", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "condition_type" },
    { no: 4, name: "event", kind: "message", T: EventExecution, oneof: "condition_type" },
  ],
);

/**
 * @generated from message zitadel.action.v3alpha.RequestExecution
 */
export const RequestExecution = /*@__PURE__*/ proto3.makeMessageType(
  "zitadel.action.v3alpha.RequestExecution",
  () => [
    { no: 1, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "condition" },
    { no: 2, name: "service", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "condition" },
    { no: 3, name: "all", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "condition" },
  ],
);

/**
 * @generated from message zitadel.action.v3alpha.ResponseExecution
 */
export const ResponseExecution = /*@__PURE__*/ proto3.makeMessageType(
  "zitadel.action.v3alpha.ResponseExecution",
  () => [
    { no: 1, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "condition" },
    { no: 2, name: "service", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "condition" },
    { no: 3, name: "all", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "condition" },
  ],
);

/**
 * @generated from message zitadel.action.v3alpha.EventExecution
 */
export const EventExecution = /*@__PURE__*/ proto3.makeMessageType(
  "zitadel.action.v3alpha.EventExecution",
  () => [
    { no: 1, name: "event", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "condition" },
    { no: 2, name: "group", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "condition" },
    { no: 3, name: "all", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "condition" },
  ],
);

