// @generated by protoc-gen-es v1.8.0
// @generated from file zitadel/action/v3alpha/target.proto (package zitadel.action.v3alpha, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Duration, proto3 } from "@bufbuild/protobuf";
import { Details } from "../../object/v2beta/object_pb.js";

/**
 * @generated from message zitadel.action.v3alpha.SetRESTWebhook
 */
export const SetRESTWebhook = /*@__PURE__*/ proto3.makeMessageType(
  "zitadel.action.v3alpha.SetRESTWebhook",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message zitadel.action.v3alpha.SetRESTRequestResponse
 */
export const SetRESTRequestResponse = /*@__PURE__*/ proto3.makeMessageType(
  "zitadel.action.v3alpha.SetRESTRequestResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message zitadel.action.v3alpha.Target
 */
export const Target = /*@__PURE__*/ proto3.makeMessageType(
  "zitadel.action.v3alpha.Target",
  () => [
    { no: 1, name: "target_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "details", kind: "message", T: Details },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "rest_webhook", kind: "message", T: SetRESTWebhook, oneof: "target_type" },
    { no: 5, name: "rest_request_response", kind: "message", T: SetRESTRequestResponse, oneof: "target_type" },
    { no: 6, name: "timeout", kind: "message", T: Duration },
    { no: 7, name: "is_async", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "execution_type" },
    { no: 8, name: "interrupt_on_error", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "execution_type" },
  ],
);

