// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file zitadel/feature/v2beta/system.proto (package zitadel.feature.v2beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { FeatureFlag, ImprovedPerformance, ImprovedPerformanceFeatureFlag } from "./feature_pb.js";
import { Details } from "../../object/v2beta/object_pb.js";

/**
 * @generated from message zitadel.feature.v2beta.SetSystemFeaturesRequest
 */
export class SetSystemFeaturesRequest extends Message<SetSystemFeaturesRequest> {
  /**
   * @generated from field: optional bool login_default_org = 1;
   */
  loginDefaultOrg?: boolean;

  /**
   * @generated from field: optional bool oidc_trigger_introspection_projections = 2;
   */
  oidcTriggerIntrospectionProjections?: boolean;

  /**
   * @generated from field: optional bool oidc_legacy_introspection = 3;
   */
  oidcLegacyIntrospection?: boolean;

  /**
   * @generated from field: optional bool user_schema = 4;
   */
  userSchema?: boolean;

  /**
   * @generated from field: optional bool oidc_token_exchange = 5;
   */
  oidcTokenExchange?: boolean;

  /**
   * @generated from field: optional bool actions = 6;
   */
  actions?: boolean;

  /**
   * @generated from field: repeated zitadel.feature.v2beta.ImprovedPerformance improved_performance = 7;
   */
  improvedPerformance: ImprovedPerformance[] = [];

  constructor(data?: PartialMessage<SetSystemFeaturesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.feature.v2beta.SetSystemFeaturesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "login_default_org", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 2, name: "oidc_trigger_introspection_projections", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 3, name: "oidc_legacy_introspection", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 4, name: "user_schema", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "oidc_token_exchange", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 6, name: "actions", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "improved_performance", kind: "enum", T: proto3.getEnumType(ImprovedPerformance), repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetSystemFeaturesRequest {
    return new SetSystemFeaturesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetSystemFeaturesRequest {
    return new SetSystemFeaturesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetSystemFeaturesRequest {
    return new SetSystemFeaturesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetSystemFeaturesRequest | PlainMessage<SetSystemFeaturesRequest> | undefined, b: SetSystemFeaturesRequest | PlainMessage<SetSystemFeaturesRequest> | undefined): boolean {
    return proto3.util.equals(SetSystemFeaturesRequest, a, b);
  }
}

/**
 * @generated from message zitadel.feature.v2beta.SetSystemFeaturesResponse
 */
export class SetSystemFeaturesResponse extends Message<SetSystemFeaturesResponse> {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: Details;

  constructor(data?: PartialMessage<SetSystemFeaturesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.feature.v2beta.SetSystemFeaturesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "details", kind: "message", T: Details },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetSystemFeaturesResponse {
    return new SetSystemFeaturesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetSystemFeaturesResponse {
    return new SetSystemFeaturesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetSystemFeaturesResponse {
    return new SetSystemFeaturesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SetSystemFeaturesResponse | PlainMessage<SetSystemFeaturesResponse> | undefined, b: SetSystemFeaturesResponse | PlainMessage<SetSystemFeaturesResponse> | undefined): boolean {
    return proto3.util.equals(SetSystemFeaturesResponse, a, b);
  }
}

/**
 * @generated from message zitadel.feature.v2beta.ResetSystemFeaturesRequest
 */
export class ResetSystemFeaturesRequest extends Message<ResetSystemFeaturesRequest> {
  constructor(data?: PartialMessage<ResetSystemFeaturesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.feature.v2beta.ResetSystemFeaturesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResetSystemFeaturesRequest {
    return new ResetSystemFeaturesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResetSystemFeaturesRequest {
    return new ResetSystemFeaturesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResetSystemFeaturesRequest {
    return new ResetSystemFeaturesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ResetSystemFeaturesRequest | PlainMessage<ResetSystemFeaturesRequest> | undefined, b: ResetSystemFeaturesRequest | PlainMessage<ResetSystemFeaturesRequest> | undefined): boolean {
    return proto3.util.equals(ResetSystemFeaturesRequest, a, b);
  }
}

/**
 * @generated from message zitadel.feature.v2beta.ResetSystemFeaturesResponse
 */
export class ResetSystemFeaturesResponse extends Message<ResetSystemFeaturesResponse> {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: Details;

  constructor(data?: PartialMessage<ResetSystemFeaturesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.feature.v2beta.ResetSystemFeaturesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "details", kind: "message", T: Details },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResetSystemFeaturesResponse {
    return new ResetSystemFeaturesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResetSystemFeaturesResponse {
    return new ResetSystemFeaturesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResetSystemFeaturesResponse {
    return new ResetSystemFeaturesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ResetSystemFeaturesResponse | PlainMessage<ResetSystemFeaturesResponse> | undefined, b: ResetSystemFeaturesResponse | PlainMessage<ResetSystemFeaturesResponse> | undefined): boolean {
    return proto3.util.equals(ResetSystemFeaturesResponse, a, b);
  }
}

/**
 * @generated from message zitadel.feature.v2beta.GetSystemFeaturesRequest
 */
export class GetSystemFeaturesRequest extends Message<GetSystemFeaturesRequest> {
  constructor(data?: PartialMessage<GetSystemFeaturesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.feature.v2beta.GetSystemFeaturesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSystemFeaturesRequest {
    return new GetSystemFeaturesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSystemFeaturesRequest {
    return new GetSystemFeaturesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSystemFeaturesRequest {
    return new GetSystemFeaturesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSystemFeaturesRequest | PlainMessage<GetSystemFeaturesRequest> | undefined, b: GetSystemFeaturesRequest | PlainMessage<GetSystemFeaturesRequest> | undefined): boolean {
    return proto3.util.equals(GetSystemFeaturesRequest, a, b);
  }
}

/**
 * @generated from message zitadel.feature.v2beta.GetSystemFeaturesResponse
 */
export class GetSystemFeaturesResponse extends Message<GetSystemFeaturesResponse> {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag login_default_org = 2;
   */
  loginDefaultOrg?: FeatureFlag;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag oidc_trigger_introspection_projections = 3;
   */
  oidcTriggerIntrospectionProjections?: FeatureFlag;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag oidc_legacy_introspection = 4;
   */
  oidcLegacyIntrospection?: FeatureFlag;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag user_schema = 5;
   */
  userSchema?: FeatureFlag;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag oidc_token_exchange = 6;
   */
  oidcTokenExchange?: FeatureFlag;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag actions = 7;
   */
  actions?: FeatureFlag;

  /**
   * @generated from field: zitadel.feature.v2beta.ImprovedPerformanceFeatureFlag improved_performance = 8;
   */
  improvedPerformance?: ImprovedPerformanceFeatureFlag;

  constructor(data?: PartialMessage<GetSystemFeaturesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "zitadel.feature.v2beta.GetSystemFeaturesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "details", kind: "message", T: Details },
    { no: 2, name: "login_default_org", kind: "message", T: FeatureFlag },
    { no: 3, name: "oidc_trigger_introspection_projections", kind: "message", T: FeatureFlag },
    { no: 4, name: "oidc_legacy_introspection", kind: "message", T: FeatureFlag },
    { no: 5, name: "user_schema", kind: "message", T: FeatureFlag },
    { no: 6, name: "oidc_token_exchange", kind: "message", T: FeatureFlag },
    { no: 7, name: "actions", kind: "message", T: FeatureFlag },
    { no: 8, name: "improved_performance", kind: "message", T: ImprovedPerformanceFeatureFlag },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSystemFeaturesResponse {
    return new GetSystemFeaturesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSystemFeaturesResponse {
    return new GetSystemFeaturesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSystemFeaturesResponse {
    return new GetSystemFeaturesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetSystemFeaturesResponse | PlainMessage<GetSystemFeaturesResponse> | undefined, b: GetSystemFeaturesResponse | PlainMessage<GetSystemFeaturesResponse> | undefined): boolean {
    return proto3.util.equals(GetSystemFeaturesResponse, a, b);
  }
}

